# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'athmovil-checkout-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for athmovil-checkout-demo
  pod 'athmovil-checkout', :path => '../'
end
