use_frameworks!
platform :ios, '10.0'

target 'athmovil-checkout_Example' do
  pod 'athmovil-checkout', :path => '../'

  target 'athmovil-checkout_Tests' do
    inherit! :search_paths
  end
end
target 'athmovil-checkout_ExampleObjC' do
    pod 'athmovil-checkout', :path => '../'
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
