disabled_rules: # rule identifiers to exclude from running
- colon
- comma
- control_statement
- trailing_whitespace
#opt_in_rules: # some rules are only opt-in
# Find all the available rules by running:
# swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
- athmovil-checkout
#excluded: # paths to ignore during linting. Takes precedence over 
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
switch_case_alignment:
    indented_cases: true
reporter: "xcode"
#, "json", "csv", "html", "markdown"